### PR TITLE
Remote control, HDR and other stuff

### PR DESCRIPTION
**Pull request by chainikdn**

### CODE REVIEW

**Comment by chainikdn** [comment]
Do you really want me spent another hour merging this?

**Comment by CrendKing** [comment]
No, don't worry about merging. I'll do it myself later.

**Comment by CrendKing** [comment]
Just FYI, I merged your commits before "Added VERSIONINFO" locally. Tested a bit and working. I see you made 4 more commits. May I ask do you plan for more commits? If yes, I'll wait for bit for you to finish. Otherwise I'll tend to them. Thanks.

**Comment by chainikdn** [comment]
I think I'm good for now.

**Pull request merged**
